package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private Integer idCalificacion;
     private Calificadora calificadora;
     private String calificacion;
     private Set valoresesForIdCalificacion3 = new HashSet(0);
     private Set valoresesForIdCalificacion1 = new HashSet(0);
     private Set valoresesForIdCalificacion2 = new HashSet(0);

    public Calificacion() {
    }

    public Calificacion(Calificadora calificadora, String calificacion, Set valoresesForIdCalificacion3, Set valoresesForIdCalificacion1, Set valoresesForIdCalificacion2) {
       this.calificadora = calificadora;
       this.calificacion = calificacion;
       this.valoresesForIdCalificacion3 = valoresesForIdCalificacion3;
       this.valoresesForIdCalificacion1 = valoresesForIdCalificacion1;
       this.valoresesForIdCalificacion2 = valoresesForIdCalificacion2;
    }
   
    public Integer getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(Integer idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Calificadora getCalificadora() {
        return this.calificadora;
    }
    
    public void setCalificadora(Calificadora calificadora) {
        this.calificadora = calificadora;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public Set getValoresesForIdCalificacion3() {
        return this.valoresesForIdCalificacion3;
    }
    
    public void setValoresesForIdCalificacion3(Set valoresesForIdCalificacion3) {
        this.valoresesForIdCalificacion3 = valoresesForIdCalificacion3;
    }
    public Set getValoresesForIdCalificacion1() {
        return this.valoresesForIdCalificacion1;
    }
    
    public void setValoresesForIdCalificacion1(Set valoresesForIdCalificacion1) {
        this.valoresesForIdCalificacion1 = valoresesForIdCalificacion1;
    }
    public Set getValoresesForIdCalificacion2() {
        return this.valoresesForIdCalificacion2;
    }
    
    public void setValoresesForIdCalificacion2(Set valoresesForIdCalificacion2) {
        this.valoresesForIdCalificacion2 = valoresesForIdCalificacion2;
    }




}


