package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Calificadora generated by hbm2java
 */
public class Calificadora  implements java.io.Serializable {


     private Integer idCalificadora;
     private String desCalificadora;
     private Set calificacions = new HashSet(0);

    public Calificadora() {
    }

    public Calificadora(String desCalificadora, Set calificacions) {
       this.desCalificadora = desCalificadora;
       this.calificacions = calificacions;
    }
   
    public Integer getIdCalificadora() {
        return this.idCalificadora;
    }
    
    public void setIdCalificadora(Integer idCalificadora) {
        this.idCalificadora = idCalificadora;
    }
    public String getDesCalificadora() {
        return this.desCalificadora;
    }
    
    public void setDesCalificadora(String desCalificadora) {
        this.desCalificadora = desCalificadora;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}


