package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Captacion generated by hbm2java
 */
public class Captacion  implements java.io.Serializable {


     private Integer idCaptacion;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private String descripcion;
     private Long idCuentaCaptacion;
     private Double monto;
     private Date fechaVencimiento;

    public Captacion() {
    }

    public Captacion(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, Long idCuentaCaptacion, Double monto, Date fechaVencimiento) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.idCuentaCaptacion = idCuentaCaptacion;
       this.monto = monto;
       this.fechaVencimiento = fechaVencimiento;
    }
   
    public Integer getIdCaptacion() {
        return this.idCaptacion;
    }
    
    public void setIdCaptacion(Integer idCaptacion) {
        this.idCaptacion = idCaptacion;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getIdCuentaCaptacion() {
        return this.idCuentaCaptacion;
    }
    
    public void setIdCuentaCaptacion(Long idCuentaCaptacion) {
        this.idCuentaCaptacion = idCuentaCaptacion;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }




}


