package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import org.apache.click.control.ActionLink;
import util.Util;

/**
 * Captacion generated by hbm2java
 */
public class Captacion implements java.io.Serializable,Comparable {


    @Override
    public int compareTo(Object t) {
        Captacion comp=(Captacion)t;
        return this.idCaptacion.compareTo(comp.getIdCaptacion());
    }
    
    /**
     * Columnas que se muestran dentro de la simulacion , metodos 
     * @return 
     */
    public static String[] getSimColumns() {
        return new String[]{"CatalogoMinimoDetail", "Descripcion", "IdCuentaCaptacion", "MontoFormato", "FechaVencimientoFormato"};
    }

    /**
     * Columnas que se muestran dentro de la simulacion, nombres
     * @return 
     */
    public static String[] getSimDesColumns() {
        return new String[]{"Catalogo Mínimo", "Descripción", "Cuenta Captación", "Monto ", "Fecha de Vencimiento"};
    }
    
    public static String getSimEditScreenName(){
        return "Captación";
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , metodos
     * @return 
     */
    public static String[] getSimNoEditColumns(){
        return new String[]{"CatalogoMinimoDetail","Descripcion","IdCuentaCaptacion"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , nombres
     * @return 
     */
    public static String[] getSimNoEditColumnsDes(){
        return new String[]{"Cuenta Contable","Descripción"," Cuenta Captación"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , metodos
     * @return 
     */
    public static String[] getSimEditColumns(){
        return new String[]{"Monto","FechaVencimiento"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , nombres
     * @return 
     */
    public static String[] getSimEditColumnsDes(){
        return new String[]{"Monto","Fecha de Vencimiento"};
    }
    

    public String getCatalogoMinimoDetail(){
        return catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    public String getMontoFormato() {
        return Util.formatNumber(getMonto());

    }

    public String getFechaVencimientoFormato() {
        return Util.formatDate(fechaVencimiento);

    }

    private Integer idCaptacion;
    private Regcuenta regcuenta;
    private Catalogocuenta catalogocuenta;
    private Date fecha;
    private String descripcion;
    private Long idCuentaCaptacion;
    private Double monto;
    private Date fechaVencimiento;
    private ActionLink simDelete;
    private ActionLink simEdit;
    
    public Captacion() {
    }

    public Captacion(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, Long idCuentaCaptacion, Double monto, Date fechaVencimiento) {
        this.regcuenta = regcuenta;
        this.catalogocuenta = catalogocuenta;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.idCuentaCaptacion = idCuentaCaptacion;
        this.monto = monto;
        this.fechaVencimiento = fechaVencimiento;
    }

    public Integer getIdCaptacion() {
        return this.idCaptacion;
    }

    public void setIdCaptacion(Integer idCaptacion) {
        this.idCaptacion = idCaptacion;
    }

    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }

    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }

    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }

    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getIdCuentaCaptacion() {
        return this.idCuentaCaptacion;
    }

    public void setIdCuentaCaptacion(Long idCuentaCaptacion) {
        this.idCuentaCaptacion = idCuentaCaptacion;
    }

    public Double getMonto() {
        return this.monto;
    }

    public void setMonto(Double monto) {
        this.monto = monto;
    }

    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }

    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

    /**
     * @return the simDelete
     */
    public ActionLink getSimDelete() {
        return simDelete;
    }

    /**
     * @param simDelete the simDelete to set
     */
    public void setSimDelete(ActionLink simDelete) {
        this.simDelete = simDelete;
    }

    /**
     * @return the simEdit
     */
    public ActionLink getSimEdit() {
        return simEdit;
    }

    /**
     * @param simEdit the simEdit to set
     */
    public void setSimEdit(ActionLink simEdit) {
        this.simEdit = simEdit;
    }


}
