package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0



/**
 * Carteraconsumo generated by hbm2java
 */
public class Carteraconsumo  implements java.io.Serializable {


     private Integer id;

    public Carteraconsumo() {
    }

   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


