package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Carteracomercial generated by hbm2java
 */
public class Carteracomercial  implements java.io.Serializable {


     private Integer idCarteraComercial;
     private Regcuenta regcuenta;
     private Date fecha;
     private Long idCuentaContable;
     private Long idCredito;
     private String descripcion;
     private Date fechaRevisionTasa;
     private Date fechaVencimiento;
     private Double capital;
     private Double interes;
     private Double saldoPagar;
     private Double saldoInsoluto;
     private Double provisionCrediticia;
     private Integer tipoCredito;
     private Integer creditoRelevante;
     private Double exposicionRiesgo;
     private Double numeroPagosFuturos;

    public Carteracomercial() {
    }

    public Carteracomercial(Regcuenta regcuenta, Date fecha, Long idCuentaContable, Long idCredito, String descripcion, Date fechaRevisionTasa, Date fechaVencimiento, Double capital, Double interes, Double saldoPagar, Double saldoInsoluto, Double provisionCrediticia, Integer tipoCredito, Integer creditoRelevante, Double exposicionRiesgo, Double numeroPagosFuturos) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.idCuentaContable = idCuentaContable;
       this.idCredito = idCredito;
       this.descripcion = descripcion;
       this.fechaRevisionTasa = fechaRevisionTasa;
       this.fechaVencimiento = fechaVencimiento;
       this.capital = capital;
       this.interes = interes;
       this.saldoPagar = saldoPagar;
       this.saldoInsoluto = saldoInsoluto;
       this.provisionCrediticia = provisionCrediticia;
       this.tipoCredito = tipoCredito;
       this.creditoRelevante = creditoRelevante;
       this.exposicionRiesgo = exposicionRiesgo;
       this.numeroPagosFuturos = numeroPagosFuturos;
    }
   
    public Integer getIdCarteraComercial() {
        return this.idCarteraComercial;
    }
    
    public void setIdCarteraComercial(Integer idCarteraComercial) {
        this.idCarteraComercial = idCarteraComercial;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getIdCuentaContable() {
        return this.idCuentaContable;
    }
    
    public void setIdCuentaContable(Long idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }
    public Long getIdCredito() {
        return this.idCredito;
    }
    
    public void setIdCredito(Long idCredito) {
        this.idCredito = idCredito;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRevisionTasa() {
        return this.fechaRevisionTasa;
    }
    
    public void setFechaRevisionTasa(Date fechaRevisionTasa) {
        this.fechaRevisionTasa = fechaRevisionTasa;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Double getCapital() {
        return this.capital;
    }
    
    public void setCapital(Double capital) {
        this.capital = capital;
    }
    public Double getInteres() {
        return this.interes;
    }
    
    public void setInteres(Double interes) {
        this.interes = interes;
    }
    public Double getSaldoPagar() {
        return this.saldoPagar;
    }
    
    public void setSaldoPagar(Double saldoPagar) {
        this.saldoPagar = saldoPagar;
    }
    public Double getSaldoInsoluto() {
        return this.saldoInsoluto;
    }
    
    public void setSaldoInsoluto(Double saldoInsoluto) {
        this.saldoInsoluto = saldoInsoluto;
    }
    public Double getProvisionCrediticia() {
        return this.provisionCrediticia;
    }
    
    public void setProvisionCrediticia(Double provisionCrediticia) {
        this.provisionCrediticia = provisionCrediticia;
    }
    public Integer getTipoCredito() {
        return this.tipoCredito;
    }
    
    public void setTipoCredito(Integer tipoCredito) {
        this.tipoCredito = tipoCredito;
    }
    public Integer getCreditoRelevante() {
        return this.creditoRelevante;
    }
    
    public void setCreditoRelevante(Integer creditoRelevante) {
        this.creditoRelevante = creditoRelevante;
    }
    public Double getExposicionRiesgo() {
        return this.exposicionRiesgo;
    }
    
    public void setExposicionRiesgo(Double exposicionRiesgo) {
        this.exposicionRiesgo = exposicionRiesgo;
    }
    public Double getNumeroPagosFuturos() {
        return this.numeroPagosFuturos;
    }
    
    public void setNumeroPagosFuturos(Double numeroPagosFuturos) {
        this.numeroPagosFuturos = numeroPagosFuturos;
    }




}


