package db.pojos;
// Generated 24/05/2014 05:59:47 PM by Hibernate Tools 3.6.0



/**
 * Carteraconsumo generated by hbm2java
 */
public class Carteraconsumo  implements java.io.Serializable {


     private Integer idCarteraConsumo;

    public Carteraconsumo() {
    }

   
    public Integer getIdCarteraConsumo() {
        return this.idCarteraConsumo;
    }
    
    public void setIdCarteraConsumo(Integer idCarteraConsumo) {
        this.idCarteraConsumo = idCarteraConsumo;
    }




}


