package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.text.NumberFormat;
import java.util.Date;
import java.util.Locale;
import org.apache.click.control.ActionLink;

/**
 * Catalogominimo generated by hbm2java
 */
public class Catalogominimo  implements java.io.Serializable {


     private Integer idCatalogoMinimo;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private Double valor;
     private Integer moneda;
     private ActionLink actionLink;
     
    public Catalogominimo() {
    }

    public Catalogominimo(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, Double valor,Integer moneda) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.valor = valor;
       this.moneda=moneda;
    }
   
    public Integer getIdCatalogoMinimo() {
        return this.idCatalogoMinimo;
    }
    
    public void setIdCatalogoMinimo(Integer idCatalogoMinimo) {
        this.idCatalogoMinimo = idCatalogoMinimo;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    /**
     * @return the moneda
     */
    public Integer getMoneda() {
        return moneda;
    }

    /**
     * @param moneda the moneda to set
     */
    public void setMoneda(Integer moneda) {
        this.moneda = moneda;
    }

 /**
     * @return the actionLink
     */
    public ActionLink getActionLink() {
        return actionLink;
    }

    /**
     * @param actionLink the actionLink to set
     */
    public void setActionLink(ActionLink actionLink) {
        this.actionLink = actionLink;
    }

    
    public String getCuenta(){
        return this.catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    public String getDetalle(){
        return this.catalogocuenta.getDesCatalogoCuenta();
    }
    
    public String getResultado(){
        Locale loc = new Locale("us");
        NumberFormat instance = NumberFormat.getInstance(loc);
        instance.setMaximumFractionDigits(2);
        try {

            return instance.format(getValor());
        }catch(Exception e){
            
        }
        return "0";
    }

}


