package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer idConfiguracion;
     private String desConfiguracion;
     private String valor;

    public Configuracion() {
    }

    public Configuracion(String desConfiguracion, String valor) {
       this.desConfiguracion = desConfiguracion;
       this.valor = valor;
    }
   
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public String getDesConfiguracion() {
        return this.desConfiguracion;
    }
    
    public void setDesConfiguracion(String desConfiguracion) {
        this.desConfiguracion = desConfiguracion;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


