package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0

/**
 * Consistencia generated by hbm2java
 */
public class Consistencia implements java.io.Serializable {

    private Integer idConsistencia;
    private Regcuenta regcuenta;
    private Double disponibilidadesLeidos;
    private Double tenenciaLeidos;
    private Double captacionLeidos;
    private Double tarjetaCreditoLeidos;
    private Double prestamosLeidos;
    private Double catalogoMinimoLeidos;
    private Double reservasLeidos;
    private Double ingresosLeidos;

    public Consistencia() {
    }

    public Consistencia(Regcuenta regCuenta, Double disponibilidadesLeidos, Double tenenciaLeidos, Double captacionLeidos, Double tarjetaCreditoLeidos, Double prestamosLeidos, Double catalogoMinimoLeidos, Double reservasLeidos, Double ingresosLeidos) {
        this.regcuenta = regCuenta;
        this.disponibilidadesLeidos = disponibilidadesLeidos;
        this.tenenciaLeidos = tenenciaLeidos;
        this.captacionLeidos = captacionLeidos;
        this.tarjetaCreditoLeidos = tarjetaCreditoLeidos;
        this.prestamosLeidos = prestamosLeidos;
        this.catalogoMinimoLeidos = catalogoMinimoLeidos;
        this.reservasLeidos = reservasLeidos;
        this.ingresosLeidos = ingresosLeidos;
    }

    public Integer getIdConsistencia() {
        return this.idConsistencia;
    }

    public void setIdConsistencia(Integer idConsistencia) {
        this.idConsistencia = idConsistencia;
    }

    public Double getDisponibilidadesLeidos() {
        return this.disponibilidadesLeidos;
    }

    public void setDisponibilidadesLeidos(Double disponibilidadesLeidos) {
        this.disponibilidadesLeidos = disponibilidadesLeidos;
    }

    public Double getTenenciaLeidos() {
        return this.tenenciaLeidos;
    }

    public void setTenenciaLeidos(Double tenenciaLeidos) {
        this.tenenciaLeidos = tenenciaLeidos;
    }

    public Double getCaptacionLeidos() {
        return this.captacionLeidos;
    }

    public void setCaptacionLeidos(Double captacionLeidos) {
        this.captacionLeidos = captacionLeidos;
    }

    public Double getTarjetaCreditoLeidos() {
        return this.tarjetaCreditoLeidos;
    }

    public void setTarjetaCreditoLeidos(Double tarjetaCreditoLeidos) {
        this.tarjetaCreditoLeidos = tarjetaCreditoLeidos;
    }

    public Double getPrestamosLeidos() {
        return this.prestamosLeidos;
    }

    public void setPrestamosLeidos(Double prestamosLeidos) {
        this.prestamosLeidos = prestamosLeidos;
    }

    public Double getCatalogoMinimoLeidos() {
        return this.catalogoMinimoLeidos;
    }

    public void setCatalogoMinimoLeidos(Double catalogoMinimoLeidos) {
        this.catalogoMinimoLeidos = catalogoMinimoLeidos;
    }

    public Double getReservasLeidos() {
        return this.reservasLeidos;
    }

    public void setReservasLeidos(Double reservasLeidos) {
        this.reservasLeidos = reservasLeidos;
    }

    public Double getIngresosLeidos() {
        return this.ingresosLeidos;
    }

    public void setIngresosLeidos(Double ingresosLeidos) {
        this.ingresosLeidos = ingresosLeidos;
    }

    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }

    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }

}
