package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;
import util.Util;

/**
 * Disponibilidad generated by hbm2java
 */
public class Disponibilidad  implements java.io.Serializable {


     private Integer idDisponibilidad;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private String descripcion;
     private Double monto;
     private Date fechaVencimiento;

    public Disponibilidad() {
    }

    public Disponibilidad(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, Double monto, Date fechaVencimiento) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.monto = monto;
       this.fechaVencimiento = fechaVencimiento;
    }
   
    public Integer getIdDisponibilidad() {
        return this.idDisponibilidad;
    }
    
    public void setIdDisponibilidad(Integer idDisponibilidad) {
        this.idDisponibilidad = idDisponibilidad;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    /**
     * Columnas que se muestran dentro de la simulacion , metodos 
     * @return 
     */
    public static String[] getSimColumns(){
        return new String[]{"IdDisponibilidad","IdCuentaContable","Descripcion","MontoFormato","FechaVencimientoFormato"};
    }
    /**
     * Columnas que se muestran dentro de la simulacion, nombres
     * @return 
     */
    public static String[] getSimDesColumns(){
        return new String[]{"ID","Cuenta Contable","Descripción","Monto","Fecha de Vencimiento"};
    }
    
    public static String getSimEditScreenName(){
        return "Disponibilidad";
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , metodos
     * @return 
     */
    public static String[] getSimNoEditColumns(){
        return new String[]{"IdCuentaContable","Descripcion","IdDisponibilidad"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , nombres
     * @return 
     */
    public static String[] getSimNoEditColumnsDes(){
        return new String[]{"Cuenta Contable","Descripción","Cuenta Disponibilidad"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , metodos
     * @return 
     */
    public static String[] getSimEditColumns(){
        return new String[]{"Monto","FechaVencimiento"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , nombres
     * @return 
     */
    public static String[] getSimEditColumnsDes(){
        return new String[]{"Monto","Fecha de Vencimiento"};
    }
    
    
    
        /**
     * saca el catalogo cuenta al que pertenece, funciona para el reporte de integridad
     * @return 
     */
    public String getCatalogoCuentaEstandar(){
        if(this.catalogocuenta==null){
            return null;
        }
        return this.catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    
    /**
     * saca el valor de la cuenta, funciona para el reporte de integridad
     * @return 
     */
    public Double getValorEstandar(){
        return this.monto;
    }
    
    public String getIdCuentaContable(){
        return catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    public String getMontoFormato(){
            return Util.formatNumber(getMonto());
    }
    
    public String getFechaVencimientoFormato(){
        return Util.formatDate(fechaVencimiento);
    }
    
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }

//es un metodo que  estandariza en todos los pojos para sacar el id de base d e datos del objeto
    public Integer getIdHeatMap(){
        return this.idDisponibilidad;
    }
    
    
        //es un metodo que se estandariza en todos los pojos para ponerle el valor al objeto en base de datos
    public void setValorHeatMap(Double value){
        setMonto(value);
    }


}


