package db.pojos;
// Generated 16/07/2014 07:26:05 PM by Hibernate Tools 3.6.0



/**
 * Emisionriesgo generated by hbm2java
 */
public class Emisionriesgo  implements java.io.Serializable {


     private Integer idEmisionRiesgo;
     private String grupoRiesgo;
     private String gradoRiesgo;
     private Double ponderador;
     private String sp;
     private String moodys;
     private String fitch;
     private String hr;

    public Emisionriesgo() {
    }

    public Emisionriesgo(String grupoRiesgo, String gradoRiesgo, Double ponderador, String sp, String moodys, String fitch, String hr) {
       this.grupoRiesgo = grupoRiesgo;
       this.gradoRiesgo = gradoRiesgo;
       this.ponderador = ponderador;
       this.sp = sp;
       this.moodys = moodys;
       this.fitch = fitch;
       this.hr = hr;
    }
   
    public Integer getIdEmisionRiesgo() {
        return this.idEmisionRiesgo;
    }
    
    public void setIdEmisionRiesgo(Integer idEmisionRiesgo) {
        this.idEmisionRiesgo = idEmisionRiesgo;
    }
    public String getGrupoRiesgo() {
        return this.grupoRiesgo;
    }
    
    public void setGrupoRiesgo(String grupoRiesgo) {
        this.grupoRiesgo = grupoRiesgo;
    }
    public String getGradoRiesgo() {
        return this.gradoRiesgo;
    }
    
    public void setGradoRiesgo(String gradoRiesgo) {
        this.gradoRiesgo = gradoRiesgo;
    }
    public Double getPonderador() {
        return this.ponderador;
    }
    
    public void setPonderador(Double ponderador) {
        this.ponderador = ponderador;
    }
    public String getSp() {
        return this.sp;
    }
    
    public void setSp(String sp) {
        this.sp = sp;
    }
    public String getMoodys() {
        return this.moodys;
    }
    
    public void setMoodys(String moodys) {
        this.moodys = moodys;
    }
    public String getFitch() {
        return this.fitch;
    }
    
    public void setFitch(String fitch) {
        this.fitch = fitch;
    }
    public String getHr() {
        return this.hr;
    }
    
    public void setHr(String hr) {
        this.hr = hr;
    }




}


