package db.pojos;
// Generated 15/07/2014 09:36:57 PM by Hibernate Tools 3.6.0



/**
 * Emision generated by hbm2java
 */
public class Emision  implements java.io.Serializable {


     private Integer idEmision;
     private String tipoValor;
     private String emision;
     private String grupoRiesgo;

    public Emision() {
    }

    public Emision(String tipoValor, String emision, String grupoRiesgo) {
       this.tipoValor = tipoValor;
       this.emision = emision;
       this.grupoRiesgo = grupoRiesgo;
    }
   
    public Integer getIdEmision() {
        return this.idEmision;
    }
    
    public void setIdEmision(Integer idEmision) {
        this.idEmision = idEmision;
    }
    public String getTipoValor() {
        return this.tipoValor;
    }
    
    public void setTipoValor(String tipoValor) {
        this.tipoValor = tipoValor;
    }
    public String getEmision() {
        return this.emision;
    }
    
    public void setEmision(String emision) {
        this.emision = emision;
    }
    public String getGrupoRiesgo() {
        return this.grupoRiesgo;
    }
    
    public void setGrupoRiesgo(String grupoRiesgo) {
        this.grupoRiesgo = grupoRiesgo;
    }




}


