package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;
import util.Util;

/**
 * Ingresosnetos generated by hbm2java
 */
public class Ingresosnetos  implements java.io.Serializable {
    
    /**
     * Columnas que se muestran dentro de la simulacion , metodos 
     * @return 
     */
    public static String[] getSimColumns() {
        return new String[]{"IdIngresosNetos","NumeroMes","IngresoNetoFormato"};
    }
    
    /**
     * Columnas que se muestran dentro de la simulacion, nombres
     * @return 
     */
    public static String[] getSimDesColumns() {
        return new String[]{"ID","Mes","Ingreso Neto"};
    }

    public static String getSimEditScreenName(){
        return "Ingresos Netos";
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , metodos
     * @return 
     */
    public static String[] getSimNoEditColumns(){
        return new String[]{"IdIngresosNetos","NumeroMes"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , nombres
     * @return 
     */
    public static String[] getSimNoEditColumnsDes(){
        return new String[]{"ID Ingreso Neto","Número de Mes"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , metodos
     * @return 
     */
    public static String[] getSimEditColumns(){
        return new String[]{"IngresoNeto"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , nombres
     * @return 
     */
    public static String[] getSimEditColumnsDes(){
        return new String[]{"Ingreso Neto"};
    }
    
    public String getIngresoNetoFormato(){
        return Util.formatNumber(getIngresoNeto());
    }



     private Integer idIngresosNetos;
     private Regcuenta regcuenta;
     private Date fecha;
     private Integer numeroMes;
     private Double ingresoNeto;
     private Double reqMerCred;

    public Ingresosnetos() {
    }

    public Ingresosnetos(Regcuenta regcuenta, Date fecha, Integer numeroMes, Double ingresoNeto,Double reqMerCred) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.numeroMes = numeroMes;
       this.ingresoNeto = ingresoNeto;
       this.reqMerCred=reqMerCred;
    }
   
    public Integer getIdIngresosNetos() {
        return this.idIngresosNetos;
    }
    
    public void setIdIngresosNetos(Integer idIngresosNetos) {
        this.idIngresosNetos = idIngresosNetos;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getNumeroMes() {
        return this.numeroMes;
    }
    
    public void setNumeroMes(Integer numeroMes) {
        this.numeroMes = numeroMes;
    }
    public Double getIngresoNeto() {
        return this.ingresoNeto;
    }
    
    public void setIngresoNeto(Double ingresoNeto) {
        this.ingresoNeto = ingresoNeto;
    }

    /**
     * @return the reqMerCred
     */
    public Double getReqMerCred() {
        return reqMerCred;
    }

    /**
     * @param reqMerCred the reqMerCred to set
     */
    public void setReqMerCred(Double reqMerCred) {
        this.reqMerCred = reqMerCred;
    }




}


