package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Ingresosnetos generated by hbm2java
 */
public class Ingresosnetos  implements java.io.Serializable {


     private Integer idIngresosNetos;
     private Regcuenta regcuenta;
     private Date fecha;
     private Integer numeroMes;
     private Double ingresoNeto;

    public Ingresosnetos() {
    }

    public Ingresosnetos(Regcuenta regcuenta, Date fecha, Integer numeroMes, Double ingresoNeto) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.numeroMes = numeroMes;
       this.ingresoNeto = ingresoNeto;
    }
   
    public Integer getIdIngresosNetos() {
        return this.idIngresosNetos;
    }
    
    public void setIdIngresosNetos(Integer idIngresosNetos) {
        this.idIngresosNetos = idIngresosNetos;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getNumeroMes() {
        return this.numeroMes;
    }
    
    public void setNumeroMes(Integer numeroMes) {
        this.numeroMes = numeroMes;
    }
    public Double getIngresoNeto() {
        return this.ingresoNeto;
    }
    
    public void setIngresoNeto(Double ingresoNeto) {
        this.ingresoNeto = ingresoNeto;
    }




}


