package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private Integer idPermiso;
     private String desPermiso;
     private String codigo;
     private Set permisosusers = new HashSet(0);

    public Permisos() {
    }

    public Permisos(String desPermiso, String codigo, Set permisosusers) {
       this.desPermiso = desPermiso;
       this.codigo = codigo;
       this.permisosusers = permisosusers;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getDesPermiso() {
        return this.desPermiso;
    }
    
    public void setDesPermiso(String desPermiso) {
        this.desPermiso = desPermiso;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getPermisosusers() {
        return this.permisosusers;
    }
    
    public void setPermisosusers(Set permisosusers) {
        this.permisosusers = permisosusers;
    }






}


