package db.pojos;
// Generated 4/06/2014 10:53:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private Integer idPermiso;
     private String desPermiso;
     private String codigo;
     private Set permisosusers = new HashSet(0);

    public Permisos() {
    }

    public Permisos(String desPermiso, Set permisosusers) {
       this.desPermiso = desPermiso;
       this.permisosusers = permisosusers;
    }
   
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }
    public String getDesPermiso() {
        return this.desPermiso;
    }
    
    public void setDesPermiso(String desPermiso) {
        this.desPermiso = desPermiso;
    }
    public Set getPermisosusers() {
        return this.permisosusers;
    }
    
    public void setPermisosusers(Set permisosusers) {
        this.permisosusers = permisosusers;
    }

    /**
     * @return the valor
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * @param valor the valor to set
     */
    public void setCodigo(String valor) {
        this.codigo = valor;
    }




}


