package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;
import util.Util;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {

    


     private Integer idPrestamo;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private String descripcion;
     private Long idCuentaPrestamo;
     private Double saldo;
     private Date fechaDeCorte;
     private String tipoPrestamo;
     private Integer relevante;

    public Prestamo() {
    }

    public Prestamo(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, Long idCuentaPrestamo, Double saldo, Date fechaDeCorte, String tipoPrestamo, Integer relevante) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.idCuentaPrestamo = idCuentaPrestamo;
       this.saldo = saldo;
       this.fechaDeCorte = fechaDeCorte;
       this.tipoPrestamo = tipoPrestamo;
       this.relevante = relevante;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getIdCuentaPrestamo() {
        return this.idCuentaPrestamo;
    }
    
    public void setIdCuentaPrestamo(Long idCuentaPrestamo) {
        this.idCuentaPrestamo = idCuentaPrestamo;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public Date getFechaDeCorte() {
        return this.fechaDeCorte;
    }
    
    public void setFechaDeCorte(Date fechaDeCorte) {
        this.fechaDeCorte = fechaDeCorte;
    }
    public String getTipoPrestamo() {
        return this.tipoPrestamo;
    }
    
    public void setTipoPrestamo(String tipoPrestamo) {
        this.tipoPrestamo = tipoPrestamo;
    }
    public Integer getRelevante() {
        return this.relevante;
    }
    
    public void setRelevante(Integer relevante) {
        this.relevante = relevante;
    }

    /**
     * Columnas que se muestran dentro de la simulacion , metodos 
     * @return 
     */
    public static String[] getSimColumns() {
        return new String[]{"IdCuentaPrestamo","IdCuentaContable","Descripcion","SaldoFormato","FechaCorteFormato","RelevanteFormato"};
    }

    /**
     * Columnas que se muestran dentro de la simulacion, nombres
     * @return 
     */
    public static String[] getSimDesColumns() {
        return new String[]{"ID","Cuenta Contable","Descripción","Saldo","Fecha de Corte","Relevante"};
    }
    
    public static String getSimEditScreenName(){
        return "Prestamo";
    }
    
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , metodos
     * @return 
     */
    public static String[] getSimNoEditColumns(){
        return new String[]{"IdCuentaContable","Descripcion","IdCuentaPrestamo","RelevanteFormato"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden editarse , nombres
     * @return 
     */
    public static String[] getSimNoEditColumnsDes(){
        return new String[]{"Cuenta Contable","Descripción","ID Prestamo","Relevante"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , metodos
     * @return 
     */
    public static String[] getSimEditColumns(){
        return new String[]{"Saldo","FechaDeCorte"};
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero  pueden editarse , nombres
     * @return 
     */
    public static String[] getSimEditColumnsDes(){
        return new String[]{"Saldo","Fecha de Corte"};
    }
    
    
    public String getIdCuentaContable(){
        return catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    public String getSaldoFormato(){
        return Util.formatNumber(getSaldo());
    }
    
    public String getFechaCorteFormato(){
        return Util.formatDate(fechaDeCorte);
    }
    
    public String getRelevanteFormato(){
        if(relevante==1){
            return "SI";
        }
        return "NO";
    }

}


