package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {

    


     private Integer idPrestamo;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private String descripcion;
     private Long idCuentaPrestamo;
     private Double saldo;
     private Date fechaDeCorte;
     private String tipoPrestamo;
     private Integer relevante;

    public Prestamo() {
    }

    public Prestamo(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, Long idCuentaPrestamo, Double saldo, Date fechaDeCorte, String tipoPrestamo, Integer relevante) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.idCuentaPrestamo = idCuentaPrestamo;
       this.saldo = saldo;
       this.fechaDeCorte = fechaDeCorte;
       this.tipoPrestamo = tipoPrestamo;
       this.relevante = relevante;
    }
   
    public Integer getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(Integer idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getIdCuentaPrestamo() {
        return this.idCuentaPrestamo;
    }
    
    public void setIdCuentaPrestamo(Long idCuentaPrestamo) {
        this.idCuentaPrestamo = idCuentaPrestamo;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public Date getFechaDeCorte() {
        return this.fechaDeCorte;
    }
    
    public void setFechaDeCorte(Date fechaDeCorte) {
        this.fechaDeCorte = fechaDeCorte;
    }
    public String getTipoPrestamo() {
        return this.tipoPrestamo;
    }
    
    public void setTipoPrestamo(String tipoPrestamo) {
        this.tipoPrestamo = tipoPrestamo;
    }
    public Integer getRelevante() {
        return this.relevante;
    }
    
    public void setRelevante(Integer relevante) {
        this.relevante = relevante;
    }


public static String[] getSimColumns() {
        return new String[]{"IdCuentaPrestamo","IdCuentaContable","Descripcion","SaldoFormato","FechaCorteFormato","RelevanteFormato"};
    }

    public static String[] getSimDesColumns() {
        return new String[]{"ID","Cuenta Contable","Descripción","Saldo","Fecha de Corte","Relevante"};
    }
    
    public String getIdCuentaContable(){
        return catalogocuenta.getIdCatalogoCuenta().toString();
    }
    
    public String getSaldoFormato(){
        Locale loc = new Locale("us");
        NumberFormat instance = NumberFormat.getInstance(loc);
        instance.setMaximumFractionDigits(2);
        try {
            return instance.format(getSaldo());
        }catch(Exception e){
            
        }
        return "0";
    }
    
    public String getFechaCorteFormato(){
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        return df.format(fechaDeCorte);
    }
    
    public String getRelevanteFormato(){
        if(relevante==1){
            return "SI";
        }
        return "NO";
    }

}


