package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Regcuenta generated by hbm2java
 */
public class Regcuenta  implements java.io.Serializable,Cloneable {


     private Integer idRegCuenta;
     private String desRegCuenta;
     private Date fecha;
     private Set disponibilidads = new HashSet(0);
     private Set carteracomercials = new HashSet(0);
     private Set valoreses = new HashSet(0);
     private Set tarjetacreditos = new HashSet(0);
     private Set regcuentausers = new HashSet(0);
     private Set cuentas = new HashSet(0);
     private Set captacions = new HashSet(0);

    public Regcuenta() {
    }

	
    public Regcuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Regcuenta(String desRegCuenta, Date fecha, Set disponibilidads, Set carteracomercials, Set valoreses, Set tarjetacreditos, Set regcuentausers, Set cuentas, Set captacions) {
       this.desRegCuenta = desRegCuenta;
       this.fecha = fecha;
       this.disponibilidads = disponibilidads;
       this.carteracomercials = carteracomercials;
       this.valoreses = valoreses;
       this.tarjetacreditos = tarjetacreditos;
       this.regcuentausers = regcuentausers;
       this.cuentas = cuentas;
       this.captacions = captacions;
    }
   
    public Integer getIdRegCuenta() {
        return this.idRegCuenta;
    }
    
    public void setIdRegCuenta(Integer idRegCuenta) {
        this.idRegCuenta = idRegCuenta;
    }
    public String getDesRegCuenta() {
        return this.desRegCuenta;
    }
    
    public void setDesRegCuenta(String desRegCuenta) {
        this.desRegCuenta = desRegCuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDisponibilidads() {
        return this.disponibilidads;
    }
    
    public void setDisponibilidads(Set disponibilidads) {
        this.disponibilidads = disponibilidads;
    }
    public Set getCarteracomercials() {
        return this.carteracomercials;
    }
    
    public void setCarteracomercials(Set carteracomercials) {
        this.carteracomercials = carteracomercials;
    }
    public Set getValoreses() {
        return this.valoreses;
    }
    
    public void setValoreses(Set valoreses) {
        this.valoreses = valoreses;
    }
    public Set getTarjetacreditos() {
        return this.tarjetacreditos;
    }
    
    public void setTarjetacreditos(Set tarjetacreditos) {
        this.tarjetacreditos = tarjetacreditos;
    }
    public Set getRegcuentausers() {
        return this.regcuentausers;
    }
    
    public void setRegcuentausers(Set regcuentausers) {
        this.regcuentausers = regcuentausers;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }
    public Set getCaptacions() {
        return this.captacions;
    }
    
    public void setCaptacions(Set captacions) {
        this.captacions = captacions;
    }


     @Override
    public String toString(){
        return String.valueOf(idRegCuenta);
    }

     @Override
    public Object clone() throws CloneNotSupportedException{
        return super.clone();
    }
    



}


