package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Regvector generated by hbm2java
 */
public class Regvector  implements java.io.Serializable {


     private Integer idRegVector;
     private Regcuenta regcuenta;
     private Date fecha;
     private String ruta;

    public Regvector() {
    }

    public Regvector(Regcuenta regcuenta, Date fecha, String ruta) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.ruta = ruta;
    }
   
    public Integer getIdRegVector() {
        return this.idRegVector;
    }
    
    public void setIdRegVector(Integer idRegVector) {
        this.idRegVector = idRegVector;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


