package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Regvector generated by hbm2java
 */
public class Regvector  implements java.io.Serializable {


     private Integer idRegVector;
     private Date fecha;
     private String ruta;

    public Regvector() {
    }

    public Regvector(Date fecha, String ruta) {
       this.fecha = fecha;
       this.ruta = ruta;
    }
   
    public Integer getIdRegVector() {
        return this.idRegVector;
    }
    
    public void setIdRegVector(Integer idRegVector) {
        this.idRegVector = idRegVector;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


