package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import util.Util;

/**
 * Tarjetacredito generated by hbm2java
 */
public class Tarjetacredito implements java.io.Serializable {

    private Integer idTarjetaCredito;
    private Regcuenta regcuenta;
    private Catalogocuenta catalogocuenta;
    private Date fecha;
    private String descripcion;
    private String idCredito;
    private Double saldoInsoluto;
    private Date fechaCorte;
    private String tipoTarjeta;
    private Integer relevante;

    public Tarjetacredito() {
    }

    public Tarjetacredito(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, String idCredito, Double saldoInsoluto, Date fechaCorte, String tipoTarjeta, Integer relevante) {
        this.regcuenta = regcuenta;
        this.catalogocuenta = catalogocuenta;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.idCredito = idCredito;
        this.saldoInsoluto = saldoInsoluto;
        this.fechaCorte = fechaCorte;
        this.tipoTarjeta = tipoTarjeta;
        this.relevante = relevante;
    }

    public Integer getIdTarjetaCredito() {
        return this.idTarjetaCredito;
    }

    public void setIdTarjetaCredito(Integer idTarjetaCredito) {
        this.idTarjetaCredito = idTarjetaCredito;
    }

    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }

    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }

    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }

    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getIdCredito() {
        return this.idCredito;
    }

    public void setIdCredito(String idCredito) {
        this.idCredito = idCredito;
    }

    public Double getSaldoInsoluto() {
        return this.saldoInsoluto;
    }

    public void setSaldoInsoluto(Double saldoInsoluto) {
        this.saldoInsoluto = saldoInsoluto;
    }

    public Date getFechaCorte() {
        return this.fechaCorte;
    }

    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }

    public String getTipoTarjeta() {
        return this.tipoTarjeta;
    }

    public void setTipoTarjeta(String tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }

    public Integer getRelevante() {
        return this.relevante;
    }

    public void setRelevante(Integer relevante) {
        this.relevante = relevante;
    }

    /**
     * Columnas que se muestran dentro de la simulacion , metodos
     *
     * @return
     */
    public static String[] getSimColumns() {                      //invertido
        return new String[]{"Descripcion", "IdCuentaContable", "IdCredito", "SaldoInsolutoFormato", "FechaCorteFormato", "RelevanteFormato"};
    }

    /**
     * Columnas que se muestran dentro de la simulacion, nombres
     * @return 
     */
    public static String[] getSimDesColumns() {
        return new String[]{"ID", "Cuenta Contable", "Descripción", "Saldo", "Fecha de Corte", "Relevante"};
    }

    
    public static String getSimEditScreenName(){
        return "Tarjeta de Crédito";
    }
    
    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden
     * editarse , metodos
     *
     * @return
     */
    public static String[] getSimNoEditColumns() {
         return new String[]{"IdCuentaContable","Descripcion","IdCredito","RelevanteFormato"};
    }

    /**
     * Son las columnas que se muestran dentro de la simulacion pero no pueden
     * editarse , nombres
     *
     * @return
     */
    public static String[] getSimNoEditColumnsDes() {
        return new String[]{"Cuenta Contable","ID Tarjeta","Descripción","Relevante"};
    }

    /**
     * Son las columnas que se muestran dentro de la simulacion pero pueden
     * editarse , metodos
     *
     * @return
     */
    public static String[] getSimEditColumns() {
        return new String[]{"SaldoInsoluto","FechaCorte"};
    }

    /**
     * Son las columnas que se muestran dentro de la simulacion pero pueden
     * editarse , nombres
     *
     * @return
     */
    public static String[] getSimEditColumnsDes() {
        return new String[]{"Saldo Insoluto","Fecha de Corte"};
    }

    public String getIdCuentaContable() {
        return catalogocuenta.getIdCatalogoCuenta().toString();
    }

    public String getSaldoInsolutoFormato() {
        return Util.formatNumber(getSaldoInsoluto());
    }

    public String getFechaCorteFormato() {
        return Util.formatDate(fechaCorte);
    }

    public String getRelevanteFormato() {
        if (relevante == 1) {
            return "SI";
        }
        return "NO";
    }
}
