package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tarjetacredito generated by hbm2java
 */
public class Tarjetacredito  implements java.io.Serializable {


     private Integer idTarjetaCredito;
     private Regcuenta regcuenta;
     private Catalogocuenta catalogocuenta;
     private Date fecha;
     private String descripcion;
     private String idCredito;
     private Double saldoInsoluto;
     private Date fechaCorte;
     private String tipoTarjeta;
     private Integer relevante;

    public Tarjetacredito() {
    }

    public Tarjetacredito(Regcuenta regcuenta, Catalogocuenta catalogocuenta, Date fecha, String descripcion, String idCredito, Double saldoInsoluto, Date fechaCorte, String tipoTarjeta, Integer relevante) {
       this.regcuenta = regcuenta;
       this.catalogocuenta = catalogocuenta;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.idCredito = idCredito;
       this.saldoInsoluto = saldoInsoluto;
       this.fechaCorte = fechaCorte;
       this.tipoTarjeta = tipoTarjeta;
       this.relevante = relevante;
    }
   
    public Integer getIdTarjetaCredito() {
        return this.idTarjetaCredito;
    }
    
    public void setIdTarjetaCredito(Integer idTarjetaCredito) {
        this.idTarjetaCredito = idTarjetaCredito;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Catalogocuenta getCatalogocuenta() {
        return this.catalogocuenta;
    }
    
    public void setCatalogocuenta(Catalogocuenta catalogocuenta) {
        this.catalogocuenta = catalogocuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIdCredito() {
        return this.idCredito;
    }
    
    public void setIdCredito(String idCredito) {
        this.idCredito = idCredito;
    }
    public Double getSaldoInsoluto() {
        return this.saldoInsoluto;
    }
    
    public void setSaldoInsoluto(Double saldoInsoluto) {
        this.saldoInsoluto = saldoInsoluto;
    }
    public Date getFechaCorte() {
        return this.fechaCorte;
    }
    
    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }
    public String getTipoTarjeta() {
        return this.tipoTarjeta;
    }
    
    public void setTipoTarjeta(String tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }
    public Integer getRelevante() {
        return this.relevante;
    }
    
    public void setRelevante(Integer relevante) {
        this.relevante = relevante;
    }




}


