package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tarjetacredito generated by hbm2java
 */
public class Tarjetacredito  implements java.io.Serializable {


     private Integer idTarjetaCredito;
     private Regcuenta regcuenta;
     private Date fecha;
     private Long idCuentaContable;
     private String idCredito;
     private String descripcion;
     private Double saldoInsoluto;
     private Date fechaCorte;
     private String tipoTarjeta;
     private Integer relevante;
     private Double provisionCrediticia;
     private Double duracion;

    public Tarjetacredito() {
    }

    public Tarjetacredito(Regcuenta regcuenta, Date fecha, Long idCuentaContable, String idCredito, String descripcion, Double saldoInsoluto, Date fechaCorte, String tipoTarjeta, Integer relevante, Double provisionCrediticia, Double duracion) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.idCuentaContable = idCuentaContable;
       this.idCredito = idCredito;
       this.descripcion = descripcion;
       this.saldoInsoluto = saldoInsoluto;
       this.fechaCorte = fechaCorte;
       this.tipoTarjeta = tipoTarjeta;
       this.relevante = relevante;
       this.provisionCrediticia = provisionCrediticia;
       this.duracion = duracion;
    }
   
    public Integer getIdTarjetaCredito() {
        return this.idTarjetaCredito;
    }
    
    public void setIdTarjetaCredito(Integer idTarjetaCredito) {
        this.idTarjetaCredito = idTarjetaCredito;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getIdCuentaContable() {
        return this.idCuentaContable;
    }
    
    public void setIdCuentaContable(Long idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }
    public String getIdCredito() {
        return this.idCredito;
    }
    
    public void setIdCredito(String idCredito) {
        this.idCredito = idCredito;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getSaldoInsoluto() {
        return this.saldoInsoluto;
    }
    
    public void setSaldoInsoluto(Double saldoInsoluto) {
        this.saldoInsoluto = saldoInsoluto;
    }
    public Date getFechaCorte() {
        return this.fechaCorte;
    }
    
    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }
    public String getTipoTarjeta() {
        return this.tipoTarjeta;
    }
    
    public void setTipoTarjeta(String tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }
    public Integer getRelevante() {
        return this.relevante;
    }
    
    public void setRelevante(Integer relevante) {
        this.relevante = relevante;
    }
    public Double getProvisionCrediticia() {
        return this.provisionCrediticia;
    }
    
    public void setProvisionCrediticia(Double provisionCrediticia) {
        this.provisionCrediticia = provisionCrediticia;
    }
    public Double getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Double duracion) {
        this.duracion = duracion;
    }




}


