package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipotasa generated by hbm2java
 */
public class Tipotasa  implements java.io.Serializable {


     private Integer idTipoTasa;
     private String desTipoTasa;
     private Integer categoria;
     private Set valoreses = new HashSet(0);

    public Tipotasa() {
    }

    public Tipotasa(String desTipoTasa, Integer categoria, Set valoreses) {
       this.desTipoTasa = desTipoTasa;
       this.categoria = categoria;
       this.valoreses = valoreses;
    }
   
    public Integer getIdTipoTasa() {
        return this.idTipoTasa;
    }
    
    public void setIdTipoTasa(Integer idTipoTasa) {
        this.idTipoTasa = idTipoTasa;
    }
    public String getDesTipoTasa() {
        return this.desTipoTasa;
    }
    
    public void setDesTipoTasa(String desTipoTasa) {
        this.desTipoTasa = desTipoTasa;
    }
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }
    public Set getValoreses() {
        return this.valoreses;
    }
    
    public void setValoreses(Set valoreses) {
        this.valoreses = valoreses;
    }




}


