package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String desTipoUsuario;
     private Set users = new HashSet(0);

    public Tipousuario() {
    }

    public Tipousuario(String desTipoUsuario, Set users) {
       this.desTipoUsuario = desTipoUsuario;
       this.users = users;
    }
   
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getDesTipoUsuario() {
        return this.desTipoUsuario;
    }
    
    public void setDesTipoUsuario(String desTipoUsuario) {
        this.desTipoUsuario = desTipoUsuario;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


