package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0



/**
 * Tipoinstrumento generated by hbm2java
 */
public class Tipoinstrumento  implements java.io.Serializable {


     private Integer idTipoInstrumento;
     private String valTipoInstrumento;
     private String desTipoInstrumento;

    public Tipoinstrumento() {
    }

    public Tipoinstrumento(String valTipoInstrumento, String desTipoInstrumento) {
       this.valTipoInstrumento = valTipoInstrumento;
       this.desTipoInstrumento = desTipoInstrumento;
    }
   
    public Integer getIdTipoInstrumento() {
        return this.idTipoInstrumento;
    }
    
    public void setIdTipoInstrumento(Integer idTipoInstrumento) {
        this.idTipoInstrumento = idTipoInstrumento;
    }
    public String getValTipoInstrumento() {
        return this.valTipoInstrumento;
    }
    
    public void setValTipoInstrumento(String valTipoInstrumento) {
        this.valTipoInstrumento = valTipoInstrumento;
    }
    public String getDesTipoInstrumento() {
        return this.desTipoInstrumento;
    }
    
    public void setDesTipoInstrumento(String desTipoInstrumento) {
        this.desTipoInstrumento = desTipoInstrumento;
    }




}


