package db.pojos;
// Generated 15/06/2015 04:43:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private int idtipousuario;
     private String nombre;
     private Tipousuario padre;
     private String permisos;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario( String nombre, Tipousuario padre, String permisos, Set usuarios) {
       this.nombre = nombre;
       this.padre = padre;
       this.permisos = permisos;
       this.usuarios = usuarios;
    }
   
    public int getIdtipousuario() {
        return this.idtipousuario;
    }
    
    public void setIdtipousuario(int idtipousuario) {
        this.idtipousuario = idtipousuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Tipousuario getPadre() {
        return this.padre;
    }
    
    public void setPadre(Tipousuario padre) {
        this.padre = padre;
    }
    public String getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(String permisos) {
        this.permisos = permisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


