package db.pojos;
// Generated 1/06/2014 08:36:24 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tracking generated by hbm2java
 */
public class Tracking  implements java.io.Serializable {


     private Integer idTracking;
     private User user;
     private String des;
     private Date fecha;

    public Tracking() {
    }

    public Tracking(User user, String des, Date fecha) {
       this.user = user;
       this.des = des;
       this.fecha = fecha;
    }
   
    public Integer getIdTracking() {
        return this.idTracking;
    }
    
    public void setIdTracking(Integer idTracking) {
        this.idTracking = idTracking;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


