package db.pojos;
// Generated 24/05/2014 05:59:47 PM by Hibernate Tools 3.6.0



/**
 * Tracking generated by hbm2java
 */
public class Tracking  implements java.io.Serializable {


     private Integer idTracking;
     private User user;
     private String des;

    public Tracking() {
    }

    public Tracking(User user, String des) {
       this.user = user;
       this.des = des;
    }
   
    public Integer getIdTracking() {
        return this.idTracking;
    }
    
    public void setIdTracking(Integer idTracking) {
        this.idTracking = idTracking;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }




}


