package db.pojos;
// Generated 24/05/2014 05:59:47 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Tipousuario tipousuario;
     private String user;
     private String password;
     private Set regcuentausers = new HashSet(0);
     private Set trackings = new HashSet(0);

    public User() {
    }

	
    public User(String user) {
        this.user = user;
    }
    public User(Tipousuario tipousuario, String user, String password, Set regcuentausers, Set trackings) {
       this.tipousuario = tipousuario;
       this.user = user;
       this.password = password;
       this.regcuentausers = regcuentausers;
       this.trackings = trackings;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getRegcuentausers() {
        return this.regcuentausers;
    }
    
    public void setRegcuentausers(Set regcuentausers) {
        this.regcuentausers = regcuentausers;
    }
    public Set getTrackings() {
        return this.trackings;
    }
    
    public void setTrackings(Set trackings) {
        this.trackings = trackings;
    }




}


