package db.pojos;
// Generated 26/06/2014 12:43:36 AM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Valores generated by hbm2java
 */
public class Valores implements java.io.Serializable {

    private Integer idTenencia;

    private Regcuenta regcuenta;
    private Date fecha;
    private Long idCuentaContable;
    private String descripcion;
    private Integer numeroTitulos;
    private String tipoValor;
    private String emision;
    private String serie;
    private Date fechaProximoCupon;
    private String grupoRc10;

    public Valores( Regcuenta regcuenta, Date fecha, Long idCuentaContable, String descripcion, Integer numeroTitulos, String tipoValor, String emision, String serie, Date fechaProximoCupon, String grupoRc10) {
        this.idTenencia = idTenencia;
        this.regcuenta = regcuenta;
        this.fecha = fecha;
        this.idCuentaContable = idCuentaContable;
        this.descripcion = descripcion;
        this.numeroTitulos = numeroTitulos;
        this.tipoValor = tipoValor;
        this.emision = emision;
        this.serie = serie;
        this.fechaProximoCupon = fechaProximoCupon;
        this.grupoRc10 = grupoRc10;
    }

    public Valores() {
    }

    public Integer getIdTenencia() {
        return this.idTenencia;
    }

    public void setIdTenencia(Integer idTenencia) {
        this.idTenencia = idTenencia;
    }

    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }

    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Long getIdCuentaContable() {
        return this.idCuentaContable;
    }

    public void setIdCuentaContable(Long idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getNumeroTitulos() {
        return this.numeroTitulos;
    }

    public void setNumeroTitulos(Integer numeroTitulos) {
        this.numeroTitulos = numeroTitulos;
    }

    public String getTipoValor() {
        return this.tipoValor;
    }

    public void setTipoValor(String tipoValor) {
        this.tipoValor = tipoValor;
    }

    public String getEmision() {
        return this.emision;
    }

    public void setEmision(String emision) {
        this.emision = emision;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Date getFechaProximoCupon() {
        return this.fechaProximoCupon;
    }

    public void setFechaProximoCupon(Date fechaProximoCupon) {
        this.fechaProximoCupon = fechaProximoCupon;
    }

    public String getGrupoRc10() {
        return this.grupoRc10;
    }

    public void setGrupoRc10(String grupoRc10) {
        this.grupoRc10 = grupoRc10;
    }

}
