package db.pojos;
// Generated 5/05/2014 10:56:00 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Valores generated by hbm2java
 */
public class Valores  implements java.io.Serializable {


     private Integer idTenencia;
     private Calificacion calificacionByIdCalificacion3;
     private Calificacion calificacionByIdCalificacion2;
     private Tipotasa tipotasa;
     private Regcuenta regcuenta;
     private Calificacion calificacionByIdCalificacion1;
     private Date fecha;
     private Long idCuentaContable;
     private String descripcion;
     private Integer numeroTitulos;
     private String tipoValor;
     private String emision;
     private String serie;
     private Date fechaVencimiento;
     private Double precioLimpio;
     private Double tasa;

    public Valores() {
    }

    public Valores(Calificacion calificacionByIdCalificacion3, Calificacion calificacionByIdCalificacion2, Tipotasa tipotasa, Regcuenta regcuenta, Calificacion calificacionByIdCalificacion1, Date fecha, Long idCuentaContable, String descripcion, Integer numeroTitulos, String tipoValor, String emision, String serie, Date fechaVencimiento, Double precioLimpio, Double tasa) {
       this.calificacionByIdCalificacion3 = calificacionByIdCalificacion3;
       this.calificacionByIdCalificacion2 = calificacionByIdCalificacion2;
       this.tipotasa = tipotasa;
       this.regcuenta = regcuenta;
       this.calificacionByIdCalificacion1 = calificacionByIdCalificacion1;
       this.fecha = fecha;
       this.idCuentaContable = idCuentaContable;
       this.descripcion = descripcion;
       this.numeroTitulos = numeroTitulos;
       this.tipoValor = tipoValor;
       this.emision = emision;
       this.serie = serie;
       this.fechaVencimiento = fechaVencimiento;
       this.precioLimpio = precioLimpio;
       this.tasa = tasa;
    }
   
    public Integer getIdTenencia() {
        return this.idTenencia;
    }
    
    public void setIdTenencia(Integer idTenencia) {
        this.idTenencia = idTenencia;
    }
    public Calificacion getCalificacionByIdCalificacion3() {
        return this.calificacionByIdCalificacion3;
    }
    
    public void setCalificacionByIdCalificacion3(Calificacion calificacionByIdCalificacion3) {
        this.calificacionByIdCalificacion3 = calificacionByIdCalificacion3;
    }
    public Calificacion getCalificacionByIdCalificacion2() {
        return this.calificacionByIdCalificacion2;
    }
    
    public void setCalificacionByIdCalificacion2(Calificacion calificacionByIdCalificacion2) {
        this.calificacionByIdCalificacion2 = calificacionByIdCalificacion2;
    }
    public Tipotasa getTipotasa() {
        return this.tipotasa;
    }
    
    public void setTipotasa(Tipotasa tipotasa) {
        this.tipotasa = tipotasa;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Calificacion getCalificacionByIdCalificacion1() {
        return this.calificacionByIdCalificacion1;
    }
    
    public void setCalificacionByIdCalificacion1(Calificacion calificacionByIdCalificacion1) {
        this.calificacionByIdCalificacion1 = calificacionByIdCalificacion1;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getIdCuentaContable() {
        return this.idCuentaContable;
    }
    
    public void setIdCuentaContable(Long idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getNumeroTitulos() {
        return this.numeroTitulos;
    }
    
    public void setNumeroTitulos(Integer numeroTitulos) {
        this.numeroTitulos = numeroTitulos;
    }
    public String getTipoValor() {
        return this.tipoValor;
    }
    
    public void setTipoValor(String tipoValor) {
        this.tipoValor = tipoValor;
    }
    public String getEmision() {
        return this.emision;
    }
    
    public void setEmision(String emision) {
        this.emision = emision;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Double getPrecioLimpio() {
        return this.precioLimpio;
    }
    
    public void setPrecioLimpio(Double precioLimpio) {
        this.precioLimpio = precioLimpio;
    }
    public Double getTasa() {
        return this.tasa;
    }
    
    public void setTasa(Double tasa) {
        this.tasa = tasa;
    }




}


