package db.pojos;
// Generated 4/06/2014 10:53:47 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Valores generated by hbm2java
 */
public class Valores  implements java.io.Serializable {


     private Integer idTenencia;
     private Regcuenta regcuenta;
     private Date fecha;
     private Long idCuentaContable;
     private String descripcion;
     private Integer numeroTitulos;
     private String tipoValor;
     private String emision;
     private String serie;
     private Date fechaVencimiento;
     private Double precioLimpio;
     private Double tasa;
     private String tipoTasa;
     private String calificacionMoodys;
     private String calificacionSp;
     private String calificacionFitch;
     private String calificacionHr;

    public Valores() {
    }

    public Valores(Regcuenta regcuenta, Date fecha, Long idCuentaContable, String descripcion, Integer numeroTitulos, String tipoValor, String emision, String serie, Date fechaVencimiento, Double precioLimpio, Double tasa, String tipoTasa, String calificacionMoodys, String calificacionSp, String calificacionFitch, String calificacionHr) {
       this.regcuenta = regcuenta;
       this.fecha = fecha;
       this.idCuentaContable = idCuentaContable;
       this.descripcion = descripcion;
       this.numeroTitulos = numeroTitulos;
       this.tipoValor = tipoValor;
       this.emision = emision;
       this.serie = serie;
       this.fechaVencimiento = fechaVencimiento;
       this.precioLimpio = precioLimpio;
       this.tasa = tasa;
       this.tipoTasa = tipoTasa;
       this.calificacionMoodys = calificacionMoodys;
       this.calificacionSp = calificacionSp;
       this.calificacionFitch = calificacionFitch;
       this.calificacionHr = calificacionHr;
    }
   
    public Integer getIdTenencia() {
        return this.idTenencia;
    }
    
    public void setIdTenencia(Integer idTenencia) {
        this.idTenencia = idTenencia;
    }
    public Regcuenta getRegcuenta() {
        return this.regcuenta;
    }
    
    public void setRegcuenta(Regcuenta regcuenta) {
        this.regcuenta = regcuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getIdCuentaContable() {
        return this.idCuentaContable;
    }
    
    public void setIdCuentaContable(Long idCuentaContable) {
        this.idCuentaContable = idCuentaContable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getNumeroTitulos() {
        return this.numeroTitulos;
    }
    
    public void setNumeroTitulos(Integer numeroTitulos) {
        this.numeroTitulos = numeroTitulos;
    }
    public String getTipoValor() {
        return this.tipoValor;
    }
    
    public void setTipoValor(String tipoValor) {
        this.tipoValor = tipoValor;
    }
    public String getEmision() {
        return this.emision;
    }
    
    public void setEmision(String emision) {
        this.emision = emision;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public Date getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(Date fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Double getPrecioLimpio() {
        return this.precioLimpio;
    }
    
    public void setPrecioLimpio(Double precioLimpio) {
        this.precioLimpio = precioLimpio;
    }
    public Double getTasa() {
        return this.tasa;
    }
    
    public void setTasa(Double tasa) {
        this.tasa = tasa;
    }
    public String getTipoTasa() {
        return this.tipoTasa;
    }
    
    public void setTipoTasa(String tipoTasa) {
        this.tipoTasa = tipoTasa;
    }
    public String getCalificacionMoodys() {
        return this.calificacionMoodys;
    }
    
    public void setCalificacionMoodys(String calificacionMoodys) {
        this.calificacionMoodys = calificacionMoodys;
    }
    public String getCalificacionSp() {
        return this.calificacionSp;
    }
    
    public void setCalificacionSp(String calificacionSp) {
        this.calificacionSp = calificacionSp;
    }
    public String getCalificacionFitch() {
        return this.calificacionFitch;
    }
    
    public void setCalificacionFitch(String calificacionFitch) {
        this.calificacionFitch = calificacionFitch;
    }
    public String getCalificacionHr() {
        return this.calificacionHr;
    }
    
    public void setCalificacionHr(String calificacionHr) {
        this.calificacionHr = calificacionHr;
    }




}


